### ISSUE TITLE
Cant find the key

### ISSUE THREAD

**Issue by castieal** [edbullen/SimpleBot#1]
Hi, as I run the file, it says can't find the key. Please help me out
![image](https://user-images.githubusercontent.com/27771189/32463121-d39e7938-c361-11e7-8744-5aa8aa332e4f.png)
![image](https://user-images.githubusercontent.com/27771189/32463079-b29a5658-c361-11e7-9bea-8f10e085fdd4.png).

I am using localhost db with simplebot name user and mypassword123 as password. Please tell the necessary changes needed

**Comment by edbullen** [comment]
Hi

Did you do this previous step:

"A separate file called ./config/.key must be created in the config
sub-directory with a single key phrase in it and no other text or
characters"

so, from the location C:\Users\rajvi\Desktop\SimpleBot-Master there should
be a sub-directory "config" with a file called .key (note the preceding
"dot")

TBH, I have not tried this on Windows - only on Linux/UNIX.  You might have
to adjust the code to pick up the key-file location ... or it might be fine
on Windows.  Please let me know.

thanks

**Comment by castieal** [comment]
Okay okay, I'll try that. Thank you
