### ISSUE TITLE
Error in "Test Database Configuration" "Setup the Database Schema"

### ISSUE THREAD

**Issue by ManoShres** [edbullen/SimpleBot#2]
I couldn't continue the steps. I am using ubuntu 18.04. I did followings and shows:

![screenshot from 2018-06-23 22-40-56](https://user-images.githubusercontent.com/31381705/41811818-9916ed66-7736-11e8-9cb1-ca1cf6db7876.png)
---
![screenshot from 2018-06-23 22-41-05](https://user-images.githubusercontent.com/31381705/41811819-997db992-7736-11e8-9c53-c92aa43a78a7.png)

**Comment by edbullen** [comment]
First line of the README - "Written in Python 3.5".
